sonar.projectKey=shopfast-app
sonar.projectName=ShopFast
sonar.projectVersion=1.2.0

sonar.sources=src/main
sonar.tests=src/test
sonar.sourceEncoding=UTF-8
sonar.qualitygate=Kotlin
sonar.qualitygate.wait=true

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=**/build/**,**/gradle/wrapper/**

sonar.coverage.exclusions=**/ShopFastApplication.kt
