name: DAST - OWASP ZAP Scan

on:
  push:
    branches:
      - teste-owasp-zap
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ShopFast (staging)
        run: docker compose up -d

      - name: Wait for app to be ready
        run: npx wait-on -t 60000 http://localhost:8080/actuator/health

      - name: Show app logs on failure
        if: failure()
        run: docker compose logs

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'http://localhost:8080/v3/api-docs'
          format: openapi
          fail_action: true