name: Pipeline de PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Tests
        run: ./gradlew build

      - name: SonarQube Scan
        run: >
          ./gradlew sonar
          -Dsonar.qualitygate.wait=true
          -Dsonar.qualitygate.timeout=300
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
